# Generated by Django 2.2.2 on 2019-06-17 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='agencies',
            table='Agencies',
        ),
    ]
