# Generated by Django 2.1.7 on 2019-06-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(db_column='Comment_id', primary_key=True, serialize=False)),
                ('comment', models.TextField(db_column='Comment')),
            ],
            options={
                'db_table': 'Comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField(db_column='Reply')),
            ],
            options={
                'db_table': 'Reply',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('city', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'Users',
                'managed': False,
            },
        ),
    ]
