# Generated by Django 2.2.2 on 2019-06-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agencies',
            fields=[
                ('agency_id', models.AutoField(db_column='Agency_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('address', models.CharField(db_column='Address', max_length=45)),
                ('e_mail', models.CharField(db_column='E-mail', max_length=45)),
                ('commercial_id', models.CharField(max_length=45)),
                ('bio', models.CharField(max_length=45)),
                ('promo_code', models.CharField(db_column='promo-code', max_length=45)),
                ('rate', models.CharField(db_column='Rate', max_length=45)),
                ('photo_url', models.TextField(db_column='photo_URL')),
            ],
            options={
                'db_table': 'Agencies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('trip_id', models.AutoField(db_column='Trip_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=50)),
                ('from_location', models.CharField(db_column='From_Location', max_length=45)),
                ('to_location', models.CharField(db_column='To_Location', max_length=45)),
                ('date_from', models.DateTimeField(db_column='Date_From')),
                ('date_to', models.DateTimeField(db_column='Date_To')),
                ('deadline', models.DateTimeField(db_column='Deadline')),
                ('meals', models.CharField(db_column='Meals', max_length=45)),
                ('price', models.FloatField(db_column='Price')),
                ('description', models.TextField(db_column='Description')),
                ('views', models.PositiveIntegerField(db_column='Views')),
                ('rate', models.FloatField(db_column='Rate')),
            ],
            options={
                'db_table': 'Trips',
                'managed': False,
            },
        ),
    ]
