# Generated by Django 2.2.2 on 2019-06-21 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_activity_users'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='Users',
        ),
    ]
